name: Deploy to Production

on:
  workflow_run:
    workflows: ["Build Docker Image"]
    types:
      - completed
    branches: [ main ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/bunkermuseum

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}

    steps:
    - name: Deploy to production server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: 91.99.224.27
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /opt/bunkermuseum

          # Log in to GitHub Container Registry
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ${{ env.REGISTRY }} -u ${{ github.actor }} --password-stdin

          # Pull latest image
          docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

          # Update docker-compose to use new image
          export IMAGE_TAG=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

          # Deploy with zero downtime
          docker compose pull app
          docker compose up -d app

          # Clean up old images
          docker image prune -f

          echo "Deployment completed successfully!"